events { worker_connections 2048; }

http {
    upstream gateway-app { server gateway-app:8000; }

    server {
        listen 80;

        # CORS headers
        add_header Access-Control-Allow-Origin  * always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
        if ($request_method = OPTIONS) { return 204; }

        location / {
            proxy_pass http://gateway-app;
        }

        access_log /dev/stdout;
    }
}
