apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestration-config
  namespace: dds25
data:
  ORCHESTRATION_MODE: "saga"
  DEV: "true"
  CHECKOUT_DEADLINE_SECONDS: "30"

# mode is either "2pl2pc" or "saga"
