apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: dds25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: openresty
          image: openresty/openresty:1.25.3.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NUM_SHARDS
              value: "3"
          volumeMounts:
            - name: nginx-conf
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: gateway-nginx-conf
